### ISSUE TITLE
Does not automatically resolve latest version

### ISSUE THREAD

**Issue by looppair** [antoineco/aco-oracle_java#23]
The [manifest](https://github.com/antoineco/aco-oracle_java/blob/a258a7029b92230dadc483829d98ba9e9c6c5bb9/manifests/init.pp#L78-L87) hard codes the latest version of Java rather than [getting it dynamically](http://stackoverflow.com/questions/12952699/java-check-latest-version-programatically). This means it's necessary to update this module to get the latest security and other updates.

**Comment by antoineco** [comment]
I'm with you, that's something I've been willing to make possible, however polling http://java.com/en/download/installed8.jsp is not enough.

When Oracle releases a new version of Java, they distribute it with a _build number_ which changes [in each release](https://github.com/antoineco/aco-oracle_java/blob/master/manifests/javalist.pp#L15-L33). This build number is needed in order to compose the download URL, which makes everything way harder.

This module provides you with some _convenience_ so that you don't have to look for this build number, look for the checksum of the released package/archive, and compose that complicated URL yourself. In _no way_ you are forced to update the module in order to update to a new version of Java though, as I said, it's just for convenience.

Imagine that [Java 1.8.0_112](https://jdk8.java.net/download.html) gets released today. It is distributed on oracle.com with the build number, for example, '08', and the expected checksum of the RPM is 'abcdefghijklmnopqrstuvwxyz1234567890'. You can update your Java version without updating this module, like this:

``` puppet
class { 'oracle_java':
  custom_download_url => 'http://download.oracle.com/otn-pub/java/jdk/8u112-b08/jdk-8u112-linux-x64.rpm',
  custom_checksum     => 'abcdefghijklmnopqrstuvwxyz1234567890'
}
```

If you have a suggestion about how to fetch all this information automatically using Puppet I'd be more than happy to try implementing it.

**Comment by antoineco** [comment]
(side note: there is a bug in the behavior I described. In [this file](https://github.com/antoineco/aco-oracle_java/blob/master/manifests/install/rpm.pp#L15) the `filename` variable is not set properly when `custom_download_url` is defined and differs from `version`. Good that you raised the issue 😃)

**Comment by antoineco** [comment]
@looppair starting from release 2.8.0 it is now slightly easier to update Java without updating the module. You still need to know the build number (and checksum if you enabled the check) but you don't have to pass the full URL to the corresponding archive anymore.

Feel free to look at the corresponding example in the documentation if you're still interested in this issue.
